#!/bin/bash
# Quick Neon Setup Helper

echo "🚀 Schdnui - Database Setup"
echo "=============================="
echo ""
echo "Follow these steps to set up your Neon PostgreSQL database:"
echo ""
echo "1️⃣  Create a Neon Account & Database:"
echo "    • Go to https://neon.tech"
echo "    • Sign up (use GitHub for quick signup)"
echo "    • Create a new project → Name: 'schdnui'"
echo "    • Copy the connection string from the dashboard"
echo ""
echo "2️⃣  Create .env.local file:"
echo "    • Run: cp .env.example .env.local"
echo "    • Open .env.local and replace DATABASE_URL with your Neon connection string"
echo "    • Example: postgresql://username:password@host/dbname?sslmode=require"
echo ""
echo "3️⃣  Initialize Database Schema:"
echo "    • Go to Neon console > SQL Editor"
echo "    • Copy-paste the entire content from lib/db-setup.sql"
echo "    • Execute the SQL"
echo ""
echo "4️⃣  Start the app:"
echo "    • Run: npm run dev"
echo "    • Open http://localhost:3000"
echo ""
echo "✅ Once DATABASE_URL is set, the app will:"
echo "   • Connect to Neon automatically"
echo "   • Save all machine and refill data to PostgreSQL"
echo "   • Sync across browsers and devices"
echo ""
echo "📚 For more info, see NEON_SETUP.md"
echo ""
